Add aarch & osx-arm64 builds
conda-forge/festival-feedstock pull request #1
Opened 2024-01-27 02:16 UTC by Tobias-Fischer

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-01-27 02:18 UTC, Tobias-Fischer commented
@conda-forge-admin, please rerender

2024-01-27 02:36 UTC, Tobias-Fischer commented
Needs https://github.com/conda-forge/libestools-feedstock/pull/4

2024-01-28 02:22 UTC, Tobias-Fischer commented
@conda-forge-admin, please rerender

2024-01-28 02:41 UTC, Tobias-Fischer commented
@conda-forge-admin, please rerender

2024-01-28 02:53 UTC, Tobias-Fischer commented
Hi @peci1 - this is ready for review :)

2024-01-31 15:56 UTC, peci1 requested changes

2024-01-31 15:56 UTC, peci1 commented on recipe/meta.yaml
>    skip: True  # [not linux]
Didn't you also want to enable osx?

2024-01-31 19:03 UTC, Tobias-Fischer commented on recipe/meta.yaml
>    skip: True  # [not linux]
Too hard for now unfortunately

2024-01-31 22:16 UTC, merged

2024-01-31 22:24 UTC, peci1 reviewed
Hmm, it seems the aarch64 build hasn't been activated by this PR...

2024-01-31 22:28 UTC, peci1 commented
Oh, now I see. The aarch64 build runs on Travis...